server:
  http_listen_address: 0.0.0.0
  grpc_listen_address: 0.0.0.0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: pbs-hooks
    static_configs:
      - targets:
          - localhost
        labels:
          job: pbs-hooks
          __path__: /var/log/pbs/hooks/*.log
